[IAM] Fix data source `identity_user_v3` (#1310)
[IAM] Fix data source `identity_user_v3`

Summary of the Pull Request
Add missing fields to identity_user_v3 data source
Fix documentation of identity_user_v3 data source
Fix #1307
PR Checklist

 Refers to: #1307
 Tests added/passed.
 Documentation updated.
 Schema updated.
 Release notes added.

Acceptance Steps Performed
With some tweaking and using microstack:
=== RUN   TestAccOpenStackIdentityV3UserDataSource_basic
    testing_new.go:70: Error running post-test destroy, there may be dangling resources: exit status 1
        
        Error: error deleting OpenStack project: Expected HTTP response code [200] when accessing [DELETE http://192.168.1.57:5000/v3/projects/1a8d23ebf4374c938a7c21d44c725bb8], but got 204 instead
        
        
--- FAIL: TestAccOpenStackIdentityV3UserDataSource_basic (8.73s)

FAIL

Process finished with the exit code 1

^^^ this is success

Reviewed-by: Rodion Gyrbu <fpsoff@outlook.com>
Reviewed-by: None <None>
Reviewed-by: Anton Sidelnikov <None>