Fix DNS zone v2 basic acceptance test (#870)
Fix DNS zone v2 basic acceptance test

Summary of the Pull Request
Separate basic and by tag tests
Test for search by tags is failing, service is returning all existing DNS zones instead of the searched one
PR Checklist

 Tests added/passed.

Acceptance Steps Performed
=== RUN   TestAccOpenStackDNSZoneV2DataSource_basic
--- PASS: TestAccOpenStackDNSZoneV2DataSource_basic (32.37s)
=== RUN   TestAccOpenStackDNSZoneV2DataSource_byTag
    testing.go:705: Step 1 error: errors during refresh:
        
        Error: your query returned more than one result. Please try a more specific search criteria
        
          on /tmp/tf-test293400622/main.tf line 15:
          (source code not available)
        
        
--- FAIL: TestAccOpenStackDNSZoneV2DataSource_byTag (13.27s)

FAIL

Process finished with exit code 1

Reviewed-by: Rodion Gyrbu <fpsoff@outlook.com>
Reviewed-by: Anton Sidelnikov <None>
Reviewed-by: None <None>